# -*- coding: utf-8 -*-
"""CleaningSupplyChainDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-Mo8TSScJ9TX0Cqoi-PSNjUmzfROKBP
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("supply_chain_data.csv")

data.head()

missing_values = data.isnull().any(axis=1)
print("Rows with missing values:")
print(missing_values)

duplicate_values = data[data.duplicated()]
print("Duplicate Rows:")
print(duplicate_values)

data.dropna(axis=0,inplace=True)

data.drop_duplicates(inplace=True)