# -*- coding: utf-8 -*-
"""CustomerSegmentationAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3zoNwT4jrixzDHccQNHvA7st0v4r2aD
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

data = pd.read_csv("supply_chain_data.csv")

data.head()

mean_revenue = data.groupby(['Customer demographics','Product type'])['Revenue generated'].mean().reset_index()

sum_revenue = data.groupby(['Customer demographics','Product type'])['Revenue generated'].sum().reset_index()

print("Mean Revenue For Each Customer Demographics")
print(mean_revenue)
print("Sum Revenue For Each Customer Demographics")
print(sum_revenue)

plt.figure(figsize=(10,6))
plt.bar(mean_revenue["Customer demographics"] + '-' + mean_revenue["Product type"], mean_revenue["Revenue generated"])
plt.xlabel("Customer Demographics - Product Type")
plt.ylabel("Mean Reveneue")
plt.title("Mean Revenue by Customer Demographics & Product Type")
plt.xticks(rotation=45,ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
plt.bar(sum_revenue["Customer demographics"] + '-' + sum_revenue["Product type"], sum_revenue["Revenue generated"])
plt.xlabel("Customer Demographics - Product Type")
plt.ylabel("Sum Reveneue")
plt.title("Sum Revenue by Customer Demographics & Product Type")
plt.xticks(rotation=45,ha='right')
plt.tight_layout()
plt.show()