# -*- coding: utf-8 -*-
"""DatasetOverview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eow0wlT0m1DjGNgOcCtuNc3Q1EEeMB5r
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("supply_chain_data.csv")

data.head(10)

data.tail()

data.info()

data.shape

data.describe()

data.columns

data.dtypes