# -*- coding: utf-8 -*-
"""InventoryOptimizationUsingEOQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQSXLsWaJbVc5rEHFMLQ70XbLd8XZ07B
"""

import pandas as pd
from google.colab import files
import numpy as np

uploaded = files.upload()

data = pd.read_csv("supply_chain_data.csv")

data.head()

holdingcost = 0.2

def calculate_eoq(data):
  D = data["Number of products sold"]
  S = data["Costs"]
  H = data["Number of products sold"] * holdingcost
  EOQ = np.sqrt((2*S*D)/H)
  return EOQ

data["Current Order Quantity"] = data["Order quantities"]

comparison_columns = ["SKU","EOQ","Current Order Quantity"]
print(data[comparison_columns])