# -*- coding: utf-8 -*-
"""SupplyChainRiskAssessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11YSGs2zEGXZCIFdhLFQT7sQm1XT0FkME
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("supply_chain_data.csv")

data.head()

selected_columns = ["SKU","Lead times","Stock levels"]

risk_data = data[selected_columns]

risk_data["Risk Score"] = risk_data["Lead times"] * (1-risk_data["Stock levels"])

risk_data = risk_data.sort_values(by="Risk Score", ascending=False)

print("Top 15 high risk SKUs")
print(risk_data.head(15))